ERROR IN PROCESSING ../dataset_preprocessing/tmpvidout.mp4
Error: __init__() got an unexpected keyword argument 'min_face_detection_confidence'
Traceback (most recent call last):
  File "/home/matteo/Documents/code/FACEXP/code/vid2h5/get_h5_from_folder.py", line 23, in get_h5
    data = videorecon(file_name, recon_model=model, loglevel='WARNING')
  File "/home/matteo/.conda/envs/medusa/lib/python3.9/site-packages/medusa/recon/recon.py", line 73, in videorecon
    reconstructor = Mediapipe(static_image_mode=False, device=device, **kwargs)
  File "/home/matteo/.conda/envs/medusa/lib/python3.9/site-packages/medusa/recon/mpipe/mpipe.py", line 48, in __init__
    self.model = mp.solutions.face_mesh.FaceMesh(
TypeError: __init__() got an unexpected keyword argument 'min_face_detection_confidence'


ERROR IN PROCESSING ../dataset_preprocessing/tmpvidout.mp4
Error: __init__() got an unexpected keyword argument 'min_face_presence_confidence'
Traceback (most recent call last):
  File "/home/matteo/Documents/code/FACEXP/code/vid2h5/get_h5_from_folder.py", line 23, in get_h5
    data = videorecon(file_name, recon_model=model, loglevel='WARNING')
  File "/home/matteo/.conda/envs/medusa/lib/python3.9/site-packages/medusa/recon/recon.py", line 73, in videorecon
    reconstructor = Mediapipe(static_image_mode=False, device=device, **kwargs)
  File "/home/matteo/.conda/envs/medusa/lib/python3.9/site-packages/medusa/recon/mpipe/mpipe.py", line 48, in __init__
    self.model = mp.solutions.face_mesh.FaceMesh(
TypeError: __init__() got an unexpected keyword argument 'min_face_presence_confidence'


ERROR IN PROCESSING ../dataset_preprocessing/tmpvidout.mp4
Error: 'BatchResults' object has no attribute 'face_idx'
Traceback (most recent call last):
  File "/home/matteo/Documents/code/FACEXP/code/vid2h5/get_h5_from_folder.py", line 23, in get_h5
    data = videorecon(file_name, recon_model=model, loglevel='WARNING')
  File "/home/matteo/.conda/envs/medusa/lib/python3.9/site-packages/medusa/recon/recon.py", line 102, in videorecon
    recon_results.filter_faces(present_threshold=0.1)
  File "/home/matteo/.conda/envs/medusa/lib/python3.9/site-packages/medusa/containers/results.py", line 137, in filter_faces
    keep = filter_faces(self.face_idx, self.n_img, present_threshold)
AttributeError: 'BatchResults' object has no attribute 'face_idx'


